Implemented code changes to add the default domainId value,
eiffel-community/eiffel-remrem-semantics pull request #139
Opened 2021-04-28 12:03 UTC by sudharshan-bandaru

if its not provided by user

### Applicable Issues

### Description of the Change
Implemented code changes to add the default domainId value, if its not provided by user.

### Alternate Designs

### Benefits
Even in the case of User is not provided the domainId REMReM-semantics will add the default domainId

### Possible Drawbacks

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Sudharshan Bandaru  sudharshan.b@tcs.com

2021-04-28 12:10 UTC, SantoshNC68 requested changes
Please add which issue it fixes, also remove the 2.1.2 version, as it is not yet released.
Make changes of the above change for 2.1.1 only

2021-04-28 12:29 UTC, sudharshan-bandaru commented
> Please add which issue it fixes, also remove the 2.1.2 version, as it is not yet released.
> Make changes of the above change for 2.1.1 only

Fixed the comments

2021-06-18 06:59 UTC, raja-maragani approved these changes
+1

2021-07-27 21:19 UTC, magnusbaeck reviewed
Why is this change being made (the linked issue gives no justification)? For sites not using multiple domains, why force events to include a domain id? For sites that _do_ use multiple domains, what's the use of a generic and rather useless "domainID" string? If you really want a domain id, why not mandate it (i.e. reject submissions without a domain id)?

2025-09-25 13:45 UTC, z-sztrom commented
Discontinued

2025-09-25 13:45 UTC, closed without merging