Add REST endpoint for listing available message protocols
eiffel-community/eiffel-remrem-semantics pull request #142
Opened 2021-11-08 12:56 UTC by vishnu-alapati

### Applicable Issues

https://github.com/eiffel-community/eiffel-remrem-generate/issues/143#

### Description of the Change

Provided implementation for getProtocolEdition() abstract method. By using this method we can return message protocol edition name.

### Alternate Designs

### Benefits

Will get more understanding about the edition which we are using.

### Possible Drawbacks

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Vishnu Alapati vishnu.alapati@tcs.com

2021-11-11 12:45 UTC, Surya-Kolli requested changes

2021-11-11 12:45 UTC, Surya-Kolli commented on src/main/java/com/ericsson/eiffel/remrem/semantics/SemanticsService.java
> +                    final InputStream is = url.openStream();
Use menaingful variable name

2021-12-06 10:53 UTC, zburswa approved these changes

2021-12-07 10:58 UTC, Umadevi-Kapu approved these changes

2021-12-07 13:08 UTC, merged